#
# Copyright (c) 2019 Kwok michael
#
# ASP booking system


config:
    version: '0.1'
    url: 'https://w6.ab.ust.hk/fbs_user/bin2/facility_booking'
    chrome_driver_binary: '/usr/local/bin/chromedriver'
    booking_hour: '06:00:00' # in HH:MM:SS format

# Required libraries:
#
# selenium
# time
# datetime
# requests
# pytz





